// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMinJF70L_YpVlL96J6_V6EVv0APm8IQ0',
    appId: '1:822793111678:android:b87c1946ed6a8f51d1f02f',
    messagingSenderId: '822793111678',
    projectId: 'fcm-test-appp',
    storageBucket: 'fcm-test-appp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsk2nQIGh5h-g8G1p8X7gBUXql_qTxOKg',
    appId: '1:822793111678:ios:b9d64931f4e3ef8ed1f02f',
    messagingSenderId: '822793111678',
    projectId: 'fcm-test-appp',
    storageBucket: 'fcm-test-appp.appspot.com',
    iosBundleId: 'com.boon.fcmtest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsk2nQIGh5h-g8G1p8X7gBUXql_qTxOKg',
    appId: '1:822793111678:ios:b9d64931f4e3ef8ed1f02f',
    messagingSenderId: '822793111678',
    projectId: 'fcm-test-appp',
    storageBucket: 'fcm-test-appp.appspot.com',
    iosBundleId: 'com.boon.fcmtest',
  );
}
